# Generated by Django 3.2.20 on 2023-12-09 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0002_auto_20180325_1433'),
    ]

    operations = [
        migrations.AddField(
            model_name='listening',
            name='source',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
