# Generated by Django 4.2.9 on 2024-04-04 15:10

from django.db import migrations


def get_user_actor(apps, schema_editor):
    MyModel = apps.get_model("history", "Listening")
    for row in MyModel.objects.all():
        actor = row.user.actor
        row.actor = actor
        row.save(update_fields=["actor"])


class Migration(migrations.Migration):
    dependencies = [
        ("history", "0004_listening_actor_listening_fid_listening_url"),
    ]

    operations = [
        migrations.RunPython(get_user_actor, reverse_code=migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="listening",
            name="user",
        ),
    ]
