# Generated by Django 4.2.9 on 2024-03-28 23:32

import uuid

from django.db import migrations, models
import django.db.models.deletion

from django.conf import settings


def gen_uuid(apps, schema_editor):
    MyModel = apps.get_model("favorites", "TrackFavorite")
    for row in MyModel.objects.all():
        row.uuid = uuid.uuid4()
        row.save(update_fields=["uuid"])


# to do : test_migration (also for listening)
class Migration(migrations.Migration):
    dependencies = [
        ("federation", "0029_userfollow"),
        ("favorites", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="trackfavorite",
            name="actor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="track_favorites",
                to="federation.actor",
            ),
        ),
        migrations.AddField(
            model_name="trackfavorite",
            name="fid",
            field=models.URLField(
                db_index=True,
                default="https://default.fid",
                max_length=500,
                unique=True,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="trackfavorite",
            name="url",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="trackfavorite",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="track_favorites",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="trackfavorite",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, null=True),
        ),
        migrations.RunPython(gen_uuid, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name="trackfavorite",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
