# Generated by Django 3.2.20 on 2023-11-29 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('favorites', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackfavorite',
            name='from_listenbrainz',
            field=models.BooleanField(default=None, null=True),
        ),
    ]
