# Generated by Django 3.2.20 on 2023-12-09 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('favorites', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackfavorite',
            name='source',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
