# Generated by Django 4.2.9 on 2024-04-04 15:56

from django.db import migrations


def get_user_actor(apps, schema_editor):
    MyModel = apps.get_model("favorites", "TrackFavorite")
    for row in MyModel.objects.all():
        actor = row.user.actor
        row.actor = actor
        row.save(update_fields=["actor"])


class Migration(migrations.Migration):
    dependencies = [
        ("federation", "0029_userfollow"),
        ("music", "0057_auto_20221118_2108"),
        ("favorites", "0002_trackfavorite_actor_trackfavorite_fid_and_more"),
    ]

    operations = [
        migrations.RunPython(get_user_actor, reverse_code=migrations.RunPython.noop),
        migrations.AlterUniqueTogether(
            name="trackfavorite",
            unique_together={("track", "actor")},
        ),
        migrations.RemoveField(
            model_name="trackfavorite",
            name="user",
        ),
    ]
