Nodeinfo:
  type: object
  required:
    - version
    - software
    - protocols
    - services
    - openRegistrations
    - usage
    - metadata
  properties:
    version:
      type: string
      enum:
        - "2.1"
    software:
      type: object
      required:
        - name
        - version
      properties:
        name:
          type: string
          enum:
            - "Funkwhale"
        version:
          type: string
          example: "1.4.0"
        repository:
          type: string
          format: url
          enum:
            - "https://dev.funkwhale.audio/funkwhale/funkwhale"
        homepage:
          type: string
          format: url
          enum:
            - "https://funkwhale.audio"
    protocols:
      type: array
      minItems: 1
      items:
        type: string
        enum:
          - "activitypub"
          - "buddycloud"
          - "dfrn"
          - "diaspora"
          - "libertree"
          - "ostatus"
          - "pumpio"
          - "tent"
          - "xmpp"
          - "zot"
      example:
        - "activitypub"
    services:
      type: object
      required:
        - inbound
        - outbound
      properties:
        inbound:
          type: array
          items:
            type: string
            enum:
              - "atom1.0"
              - "gnusocial"
              - "imap"
              - "pnut"
              - "pop3"
              - "pumpio"
              - "rss2.0"
              - "twitter"
        outbound:
          type: array
          items:
            type: string
            enum:
              - "atom1.0"
              - "blogger"
              - "buddycloud"
              - "diaspora"
              - "dreamwidth"
              - "drupal"
              - "facebook"
              - "friendica"
              - "gnusocial"
              - "google"
              - "insanejournal"
              - "libertree"
              - "linkedin"
              - "livejournal"
              - "mediagoblin"
              - "myspace"
              - "pinterest"
              - "pnut"
              - "posterous"
              - "pumpio"
              - "redmatrix"
              - "rss2.0"
              - "smtp"
              - "tent"
              - "tumblr"
              - "twitter"
              - "wordpress"
              - "xmpp"
    openRegistrations:
      type: boolean
    usage:
      type: object
      required:
        - users
      properties:
        users:
          type: object
          properties:
            total:
              type: integer
              minimum: 0
            activeHalfYear:
              type: integer
              minimum: 0
            activeMonth:
              type: integer
              minimum: 0
        localPosts:
          type: integer
          minimum: 0
        localComments:
          type: integer
          minimum: 0
    metadata:
      type: object
      properties:
        actorId:
          type: string
          format: url
        private:
          type: boolean
        shortDescription:
          type: string
        longDescription:
          type: string
        contactEmail:
          type: string
          format: email
        nodeName:
          type: string
        banner:
          type: string
          format: url
          nullable: true
        defaultUploadQuota:
          type: integer
        supportedUploadExtensions:
          type: array
          items:
            type: string
        allowList:
          type: object
          properties:
            enabled:
              type: boolean
            domains:
              type: array
              nullable: true
              items:
                type: string
        funkwhaleSupportMessageEnabled:
          type: boolean
        instanceSupportMessage:
          type: string
        languages:
          type: array
          items:
            type: string
        location:
          type: string
        content:
          type: object
          properties:
            local:
              type: object
              properties:
                artists:
                  type: number
                releases:
                  type: number
                recordings:
                  type: number
                hoursOfContent:
                  type: number
              example:
                artists: 1000
                releases: 10000
                recordings: 150000
                hoursOfContent: 7500
            topMusicCategories:
              type: array
              items:
                type: object
                properties:
                  name:
                    type: string
                  count:
                    type: integer
                    minimum: 0
              example:
                - name: "rock"
                  count: 1256
                - name: "jazz"
                  count: 604
                - name: "classical"
                  count: 308
            topPodcastCategories:
              type: array
              items:
                type: object
                properties:
                  name:
                    type: string
                  count:
                    type: integer
                    minimum: 0
              example:
                - name: "comedy"
                  count: 12
                - name: "politics"
                  count: 4
                - name: "nature"
                  count: 1
            federation:
              type: object
              properties:
                followedInstances:
                  type: integer
                followingInstances:
                  type: integer
        usage:
          type: object
          properties:
            listenings:
              type: integer
              minimum: 0
            downloads:
              type: integer
              minimum: 0
            favorites:
              type: object
              properties:
                tracks:
                  type: integer
                  minimum: 0
        features:
          type: array
          items:
            type: string
          example:
            - "channels"
            - "podcasts"
            - "collections"
            - "audiobooks"
            - "federation"
            - "anonymousCanListen"
