# Generated by Django 4.2.9 on 2024-04-18 17:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0023_merge_20221125_1902"),
        ("federation", "0030_actor_privacy_level"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="privacy_level",
        ),
    ]
