# Generated by Django 3.2.18 on 2023-06-13 21:23

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radios', '0007_merge_20220715_0801'),
    ]

    operations = [
        migrations.AddField(
            model_name='radiosessiontrack',
            name='played',
            field=models.BooleanField(default=False),
        ),
    ]
