# Generated by Django 3.2.20 on 2023-09-16 15:04

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radios', '0007_merge_20220715_0801'),
    ]

    operations = [
        migrations.AddField(
            model_name='radiosession',
            name='api_version',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='radiosession',
            name='config',
            field=models.JSONField(blank=True, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True),
        ),
    ]
