# Generated by Django 4.2.9 on 2024-05-12 12:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("music", "0057_auto_20221118_2108"),
    ]

    operations = [
        migrations.AddField(
            model_name="artist",
            name="guid",
            field=models.UUIDField(default=uuid.uuid4, null=True),
        ),
    ]
