# Generated by Django 4.2.9 on 2024-05-12 12:39

from django.db import migrations
import uuid


def gen_uuid(apps, schema_editor):
    ArtistModel = apps.get_model("music", "artist")
    for row in ArtistModel.objects.all():
        row.guid = uuid.uuid4()
        row.save(update_fields=["guid"])


class Migration(migrations.Migration):
    dependencies = [
        ("music", "0058_add_artist_guid"),
    ]

    operations = [
        migrations.RunPython(gen_uuid, reverse_code=migrations.RunPython.noop),
    ]
