# Generated by Django 3.2.23 on 2024-01-15 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("music", "0058_uploadgroup"),
    ]

    operations = [
        migrations.AddField(
            model_name="upload",
            name="upload_group",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="uploads",
                to="music.uploadgroup",
            ),
        ),
    ]
