# Generated by Django 4.2.9 on 2024-05-12 12:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("music", "0059_generate_artist_guid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="artist",
            name="guid",
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
