# Generated by Django 3.2.23 on 2024-01-15 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("music", "0060_auto_20240115_1055"),
    ]

    operations = [
        migrations.AlterField(
            model_name="upload",
            name="upload_group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="uploads",
                to="music.uploadgroup",
            ),
        ),
    ]
