# Generated by Django 3.2.23 on 2024-01-22 13:58

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("federation", "0028_auto_20221027_1141"),
        ("music", "0062_alter_upload_upload_group"),
    ]

    operations = [
        migrations.AddField(
            model_name="uploadgroup",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="uploadgroup",
            name="owner",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="upload_groups",
                to="federation.actor",
            ),
            preserve_default=False,
        ),
    ]
