SimpleArtist:
  type: object
  required:
    - guid
    - fid
    - name
    - contentCategory
    - local
  properties:
    guid:
      type: string
      format: uuid
      description: "The globally unique ID of the artist"
    fid:
      type: string
      format: url
    mbid:
      type: string
      format: uuid
    name:
      type: string
    contentCategory:
      type: string
      enum:
        - music
        - podcast
        - other
    local:
      type: boolean
    channel:
      type: string
      format: uuid
Artist:
  allOf:
    - $ref: "#/SimpleArtist"
    - type: object
      required:
        - creationDate
        - recordingCount
        - releases
      properties:
        creationDate:
          type: string
          format: date-time
          description: "The date on which the artist was added to the server"
        recordingCount:
          type: integer
          description: "The number of recordings credited to the artist"
        tags:
          type: array
          items:
            type: string
          description: "Any tags associated with the artist"
        releases:
          type: array
          items:
            $ref: "../../schema.yml#/components/schemas/SimpleRelease"
        collections:
          type: array
          items:
            $ref: "../collections/schema.yml#/SimpleCollection"
ArtistCredit:
  type: object
  required:
    - name
    - guid
  properties:
    name:
      type: string
      description: "The name of the artist"
    guid:
      type: string
      format: uuid
      description: "The globally unique ID of the artist"
    joinPhrase:
      type: string
      description: "The phrase used to join this artist's name in the credits. For example: 'feat', '&', '+'"
